#!/bin/bash

    # Run GEMMA  ======================================================================
    for MODEL in ${MODEL_GEMMA}; do
        for NC in ${NGEMMA}; do
            SPECIFIC_JOBSUBDIR="${THIS_JOBSUBDIR}/${GEMMA_JOBSUBDIR}/c${NC}_1e6_${MODEL}"
            if [ -d ${SPECIFIC_JOBSUBDIR} ]; then rm -rf ${SPECIFIC_JOBSUBDIR}; fi
            mkdir -p ${SPECIFIC_JOBSUBDIR}
            cd ${SPECIFIC_JOBSUBDIR}
    
            while read LOCUSPREFIX; do
                GEMMA_JOBNAME="gemma_${SIM}_c${NC}_${MODEL}_${LOCUSPREFIX}_${RANDSTRING}"
                sed -e "s|_JOBNAME|${GEMMA_JOBNAME}|g;
                        s|_SIMDIR_|${THIS_SIMDIR}|g;
                        s|_STUDYN_|\"${STUDYNAMES[*]}\"|g;
                        s|_LOCUSP_|${LOCUSPREFIX}|g;
                        s|_LOCIDIR|${DOSAGEDIR}|g;
                        s|_NCAUSAL|${NC}|g;
                        s|_MODEL__|${MODEL}|g;
                        s|_GEMMA__|${GEMMA}|g;
                        s|_USE_COV|${USE_AGESEX}|g;
                       " ${MASTER_BSUBDIR}/gemma.bsub > ${GEMMA_JOBNAME}.bsub
                if [ "${bRegCov}" = "true" ]; then 
                    bsub -w "done(${REGRESS_JOBNAME})" < ${GEMMA_JOBNAME}.bsub
                else
                    if [ "${bMakePheno}" = "true" ]; then
                        bsub -w "done(${PHENO_JOBNAME})" < ${GEMMA_JOBNAME}.bsub
                    else
                        bsub < ${GEMMA_JOBNAME}.bsub
                    fi
                fi
            done < ${BIGLOCUS}
            cd ${THIS_JOBSUBDIR}
        done
    done
    # =================================================================================
