#!/bin/bash

CURDIR=`pwd`

# Parameters
STUDYNAMES=('G1' 'G2' 'G3' 'G4' 'G5')
STUDYSAMPLES=('2139' '2420' '2472' '2084' '3967')
OLDIFS=$IFS; IFS="+"
NSAMPLE_TOT=`echo "${STUDYSAMPLES[*]}" | bc`
IFS=$OLDIFS

# data directories
BASEDIR="/scratch/sbanerj/quasi_laplace_single_region"
COPYFROM="/scratch/sbanerj/quasi_laplace_gwas/input_files"
REF_DOSAGEDIR="${COPYFROM}/loci_dosages"
REF_LOCUSNAMES="${COPYFROM}/LOCUSNAMES"

DOSAGEDIR="${BASEDIR}/loci_dosages"
SIMDIR="${BASEDIR}/simulations"
LOCUSNAMES="${BASEDIR}/LOCUSNAMES"
USELOCI="${BASEDIR}/LOCUSNAMES.MAXSNPS"
BIGLOCUS="${BASEDIR}/BIGLOCUSNAME"
SAMPLEPREFIX="_QC_age"

# Pipeline directories
SCRIPTDIR="${CURDIR}/../scripts"
MASTER_BSUBDIR="${CURDIR}/../bsubfiles"
JOBSUBDIR="${CURDIR}/../jobsubs"
LDBASEDIR="${BASEDIR}/ldmap"
LDMAPWGHTDIR="${BASEDIR}/ldmap/weighted"
LDMAPCOMBDIR="${BASEDIR}/ldmap/combined"
POSTPROBDIR="${CURDIR}/../analysis/posterior_prob"

# external programs required for the pipeline
SNPTEST="${HOME}/packages/SNPTEST/snptest_v2.5.4-beta3_linux_x86_64_dynamic/snptest_v2.5.4-beta3"
META="${HOME}/packages/META/meta"
LDSTORE="${HOME}/packages/ldstore/ldstore_v1.1_x86_64/ldstore"
BLORE="${HOME}/fine-mapping-SNPs/codebase/b-lore/bin/blore"
PIMASS="${HOME}/packages/pimass/pimass/pimass"
FINEMAP="${HOME}/packages/FINEMAP/finemap_v1.1_x86_64/finemap"
QCTOOL="${HOME}/packages/qctool/qctool_v1.4-linux-x86_64/qctool"
GEMMA="gemma"
## BIMBAM="${HOME}/packages/BIMBAM/bimbam/bimbam"

# other scripts used in the pipeline
GENINF="${SCRIPTDIR}/genomic_inflation_factor.py"
LDMAP_WEIGHTED="${SCRIPTDIR}/ldmap_weighted.py"
CREATEPHENO="${SCRIPTDIR}/create_phenotype.py"
CREATELOCI="${SCRIPTDIR}/create_loci.py"
REGRESS_COVARIATES="${SCRIPTDIR}/regress_covariates.py"
PLOTPIP="${POSTPROBDIR}/plot_pip.py"

# if [ -f ${LOCUSNAMES} ]; then IFS=$'\r\n' GLOBIGNORE='*' command eval 'LOCIPREFIX=($(cat ${LOCUSNAMES}))'; fi
